### ISSUE TITLE
[Warning] About spreading the exe file

### ISSUE THREAD

**Issue by MysteryDash** [SilicaAndPina/PS4RemotePlayPATCH#1]
Hello,

I understand it is quite useful for the users of the PS4 Remote Play to get the modified version already pre-patched, without having to deal with the trouble of [following a small guide](https://github.com/MysteryDash/Offline-PS4-Remote-Play), however, as I stated in my repository, spreading the modified executable can cause you trouble if Sony doesn't like it.

I personally believe that I am in a grey area as I only give you the means of achieving the result, without sharing Sony's actual intellectual property (I even gave a method to achieve this result without having to mess around with Sony's software). However, considering that you are sharing a patched software made by Sony, trouble may arise (you are literally breaking [Sony's Terms of Use](https://www.playstation.com/en-us/network/legal/terms-of-service/) in an obvious way).

Also, adding a link to my repository in your readme would be great if you based your work on mine.

EDIT : Forking my repository would have satisfied me too.

**Comment by SilicaAndPina** [comment]
I will update the readme with a link to your patch as that is where i got my general idea from :3 (however i have somewhat implemented it differently.)

as for distributing the patched .exe i could and probably should make xdelta patch files for them.
but at the same time if sony came after my GIT i would be screwed anyway due to repos like Cex2Rex and Firmware reinstaller. . .
